<?php
/**
 * Copyright © 2016 Pheme. All rights reserved.
 */

/*
 * @var $this \Pheme\Facebook\Block\AsyncInit
 * */
?>
<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/<?php echo $this->getLocale() ?>/sdk.js#xfbml=1&version=v2.5";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>